name = "hop"
workers_dev = false
compatibility_date = "2022-01-20"
main = "build/worker/shim.mjs"
routes = [
	{ pattern = "hop.jiahua.io", custom_domain = true }
]

[vars]

[build]
command = "worker-build --release"

[dev]
port = 8787

[[rules]]
fallthrough = true
globs = ["**/*.wasm"]
type = "CompiledWasm"
